"""table: image, add column: favorite

Revision ID: 75b54db3960d
Revises: 3eaa788c373b
Create Date: 2016-03-20 21:27:25.873133

"""

# revision identifiers, used by Alembic.
revision = '75b54db3960d'
down_revision = '3eaa788c373b'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from wallp.db.model.all import Base


def upgrade():
	### commands auto generated by Alembic - please adjust! ###
	op.add_column('image', sa.Column('favorite', sa.Boolean(), nullable=True))
	### end Alembic commands ###
	connection = op.get_bind()
	#import pdb; pdb.set_trace()
	image = Base.metadata.tables['image']
	connection.execute(image.update().values(favorite=False))


def downgrade():
	### commands auto generated by Alembic - please adjust! ###
	op.drop_column('image', 'favorite')
	### end Alembic commands ###
